### ISSUE TITLE
React has detected a change in the order of Hooks called by EmotionCssPropInternal

### ISSUE THREAD

**Issue by nubbdev** [dennismorello/react-awesome-reveal#59] opened 2020-11-22 12:33 UTC
Hi, I'm just installed and put some Fade effect on my Component and I got some error message like this :

![Screenshot 2020-11-22 192130](https://user-images.githubusercontent.com/22774254/99903665-42d99780-2cf8-11eb-858b-392da9c8b45c.png)

I use this :
`<Fade direction="top" duration={500}>
.....
</Fade>
`

This is from me or the package? Tell me how I can solve
Thank you for sharing awesome package, I'm really enjoyed

**Comment by dennismorello** [comment] 2020-11-22 12:46
This is a duplicate of #57.

**Closed** 2020-11-22 12:46 UTC
Labels: duplicate

**Comment by nubbdev** [comment] 2020-11-23 06:17
Thankyou @dennismorello
