### ISSUE TITLE
Accessibility TabIndex

### ISSUE THREAD

**Issue by VGamezz19** [dennismorello/react-awesome-reveal#21] opened 2020-02-06 14:47 UTC
Hey,

First of all, i really apreciaty this kind of NPM package that helps alote to the community.

after that, i'm wandering how can I TabIndex, in the elements, and how can we use ur package in a accessibility way!.

this is my example, and when i'm traying to do TAB it never stop. How can we do it possible?

````
  <Fade direction="bottom">
              <h2 tabIndex="0" tabIndex className="explore-the-future-of-data__title">
                {t(`${TRANSLATION_SUFIX}.save-the-day.title-1`)}
                <br />
                {t(`${TRANSLATION_SUFIX}.save-the-day.title-2`)}
              </h2>
            </Fade>
            <Fade direction="left" cascade>
              <h3 tabIndex="1" className="explore-the-future-of-data__subtitle">{t(`${TRANSLATION_SUFIX}.save-the-day.title-3`)}</h3>
              <p tabIndex="2">{t(`${TRANSLATION_SUFIX}.save-the-day.description-1`)}</p>
              <p tabIndex="3">{t(`${TRANSLATION_SUFIX}.save-the-day.description-2`)}</p>
            </Fade>
```

**Comment by dennismorello** [comment] 2020-02-06 16:03
Hi @VGamezz19,

thank you for appreciating the library!

I tried to reproduce your code (without the translation library), and I have no issue at all:

```javascript
<Fade direction="bottom">
  <h2 tabIndex="1" className="explore-the-future-of-data__title">
     A<br />B
   </h2>
 </Fade>
 <Fade direction="left" cascade>
   <h3 tabIndex="2" className="explore-the-future-of-data__subtitle">C</h3>
   <p tabIndex="3">D</p>
   <p tabIndex="4">E</p>
</Fade>
```

![react-awesome-reveal-tabindex](https://user-images.githubusercontent.com/19588613/73954429-1b991180-4902-11ea-9a76-729f8267e551.gif)

The only thing I see is a wrong sequence of attributes `tabIndex="0" tabIndex` in the first `<h2>` tag you wrote.

Let me know if it helps, so I can close the issue.

**Comment by VGamezz19** [comment] 2020-02-06 22:07
yep! sorry I just explained in a wrong way. Those items are out of boundary (i miss explain this important point hehe) you must to scroll to reach them. 
So they still hidded before I press Tab. As I can picture, this element dosen't exist yet...

**Comment by dennismorello** [comment] 2020-02-08 12:00
No, the elements are mounted when your component wrapping them is rendered.

By default, all elements not in the viewport are not visible (they have `visibility: hidden` CSS rule set) *but* they do exist in the DOM – they are watched by an IntersectionObserver instance that triggers the animation when they enter the viewport.

The "issue" here is that when you jump to an element by pressing the TAB key, if that element is not visible (because, in this case, it has the rule `visibility: hidden` set), it won't be focusable.

I will find a fix for that keeping accessibility in mind; for now, a temporary workaround could be setting the `triggerOnce` prop so that you can focus elements once the animations have been run.

**Closed** 2020-02-08 12:08 UTC
Labels: bug

**Comment by dennismorello** [comment] 2020-02-08 12:10
@VGamezz19 please update to version `2.4.2`.
