### ISSUE TITLE
Performance is worse with multiple animation  

### ISSUE THREAD

**Issue by rizkyramadhan** [dennismorello/react-awesome-reveal#48] opened 2020-10-02 23:39 UTC
Coming from react-reveal, and I am noticing that react-awesome-reveal animation is jittery and scrolling is janky when there are multiple animation played. Esepecially in animation heavy landing page.

Sorry but I can't create codesandbox at the moment, will do when I have the time. For now, I just informing my experience...

**Comment by dennismorello** [comment] 2020-10-16 05:49
This looks strange... Which browser and hardware are you using?

**Comment by dennismorello** [comment] 2020-11-02 08:18
I'm closing this because I cannot reproduce.

**Closed by dennismorello** 2020-11-02 08:18 UTC
