### ISSUE TITLE
React Hooks warning, possibly related to Emotion

### ISSUE THREAD

**Issue by albertcarrete** [dennismorello/react-awesome-reveal#58] opened 2020-11-20 07:09 UTC
I've been receiving this warning while using react-awesome-reveal lately. Seems to be related to Emotion. 

```
Warning: React has detected a change in the order of Hooks called by EmotionCssPropInternal.
This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks:
https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. undefined                  useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I've attached [a simple Codesandbox](https://codesandbox.io/s/youthful-worker-9p962?file=/src/App.js) that contains React v17 and this package that shows the error.

**Comment by dennismorello** [comment] 2020-11-20 07:10
Duplicate of #57.

**Comment by dennismorello** [comment] 2020-11-20 07:12
Please use version 3.4.0 as a temporary fix.

**Comment by albertcarrete** [comment] 2020-11-20 07:13
I must be tired, please ignore. Feel free to close, thanks!

**Closed** 2020-11-20 07:14 UTC
Labels: duplicate
