### ISSUE TITLE
Change in the order of Hooks

### ISSUE THREAD

**Issue by JayeshTiwari03** [dennismorello/react-awesome-reveal#64] opened 2020-12-17 18:57 UTC
Getting following Warning in console when trying to use Fade. Has anyone came across this before?

```
React has detected a change in the order of Hooks called by EmotionCssPropInternal. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. undefined                  useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at EmotionCssPropInternal (http://localhost:3000/Portfolio/static/js/0.chunk.js:555:73)
    at InView (http://localhost:3000/Portfolio/static/js/0.chunk.js:40435:30)
    at Reveal (http://localhost:3000/Portfolio/static/js/0.chunk.js:9910:27)
    at Fade (http://localhost:3000/Portfolio/static/js/0.chunk.js:10975:23)
    at div
    at div
    at Home
    at Route (http://localhost:3000/Portfolio/static/js/0.chunk.js:42168:29)
    at Switch (http://localhost:3000/Portfolio/static/js/0.chunk.js:42370:29)
    at Router (http://localhost:3000/Portfolio/static/js/0.chunk.js:41803:30)
    at BrowserRouter (http://localhost:3000/Portfolio/static/js/0.chunk.js:41423:35)
    at div
    at Routes
    at div
    at App
```

**Comment by dennismorello** [comment] 2020-12-17 19:34
Duplicate of #57

**Closed** 2020-12-17 19:33 UTC
Labels: duplicate

**Comment by JayeshTiwari03** [comment] 2020-12-18 06:41
Thanks
